version: '3.7'
services:

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        container_name: ondemand-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ondemandDev
            MYSQL_ROOT_PASSWORD: ondemandDev
            MYSQL_PASSWORD: 123secret
            MYSQL_USER: ondemandDev
            SERVICE_NAME: mysql
        ports:
            - "3666:3306"

    redis:
        image: redis:6.2-alpine
        container_name: 'redis-server-caching'
        ports:
            - '6379:6379'

