version: '3.7'
services:

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        container_name: ondemand-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq-ondemand'
        ports:
            - '5672:5672'
            - '15672:15672'


    redis:
        image: redis:6.2-alpine
        container_name: 'redis-server-caching'
        ports:
            - '6379:6379'


    stripe-cli:
        image: stripe/stripe-cli
        container_name: 'stripe-cli'
        command:
            listen --api-key ${STRIPE_SECRET} --forward-to 192.168.0.175:8000/stripe/webhook


#    stripe-cli-trigger:
#        image: stripe/stripe-cli
#        container_name: 'stripe-cli-trigger'
#        command: trigger invoice.payment_succeeded --api-key ${STRIPE_SECRET}

